services:
  app:
    build:
      context: .
      network: host
    network_mode: host
    environment:
      - PORT=3000
      - OPCUA_TCP_PORT=4840
      - OPCUA_ENDPOINT_URL=opc.wss://yourdomain.com/opcua
    restart: unless-stopped
